### ISSUE TITLE
Do i need to do face alignment before test my own face pictures?

### ISSUE THREAD

**Issue by BELZHANG** [wy1iu/sphereface#104]
Hi all, I check the evaluation.m and noticed that there is no preprocess before extract face features. Does it mean I don't need to do the face alignment before feed my face picture into the net during test?

Thank you！

**Comment by phoebushe** [comment]
You should do the face alignment before the TESTING.

**Comment by BELZHANG** [comment]
Thank you, i noticed that the lfw test images are aligned.
