### ISSUE TITLE
Is any one know how to plot the Fig. 5 in paper? What type of tool is required to achieve this?

### ISSUE THREAD

**Issue by lizhaoliu-Lec** [wy1iu/sphereface#136]

**Comment by CloudWalking0** [comment]
> _No description provided._

Hello, I'm wondering if you know how to plot the Fig. 5 now? It's really important to me. Thank you!

**Comment by lizhaoliu-Lec** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            The issue has been resolved.I initially implemented a rough version using python's matplotlib (code and visualization are attached).Later, other students in the lab also used matlab to draw a version, which will be much better than my version in terms of color and 3D effect, but the code can not be found, you can try it with matlab
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    On 3/23/2022 ***@***.***> wrote： 




No description provided.

Hello, I'm wondering if you know how to plot the Fig. 5 now? It's really important to me. Thank you!
