### ISSUE TITLE
caffe-face features

### ISSUE THREAD

**Issue by bkj** [wy1iu/sphereface#16]
Hi --

This is a question better directed at the https://github.com/ydwen/caffe-face issues, but issues are disabled and that project was written by some of the same authors.

The LFW features are available for download on the `caffe-face` projects page -- is there evaluation code available to reproduce the 99% accuracy reported in the paper?  The paper mentions using PCA on the features, but I haven't been able to get that kind of accuracy using the pretrained vectors.  Any ideas?

Thanks

**Comment by wy1iu** [comment]
Sorry I have to close the issue, since it is not related to sphereface. Thanks.
