### ISSUE TITLE
Mirroring and Multi-patch approach

### ISSUE THREAD

**Issue by commanderka** [wy1iu/sphereface#19]
Hi,

in the figures of your papers you can see that the 3-patch net outperforms the one patch net and you say that the 3-patch feature vector is formed by concatenating the feature vectors of each patch. However, you do not say in your paper how these patches are computed. Do you use a different alignment strategy and train a new net on each type of aligned images or do you introduce a small offset and extract the 3-patch features by just transforming the original image a bit and computing the features with the original net?
Furthermore I get better results when not concatenating the features of the mirrored image. Has anyone experimented on that (patch selection/(not) mirroring) ?

**Comment by commanderka** [comment]
I have to take back my last statement. Concatenating the mirrored features improves the results. Nevertheless, I would be interested in more details concerning the multi patch approach.

**Comment by CasiaFan** [comment]
@wy1iu Could you tell us a little bit more information about your patch selection? I know one method is to crop original image centered at specific landmarks and train a new net for each.

**Comment by wy1iu** [comment]
@CasiaFan Yes, you are right. Three-patch ensemble in the paper is to train three networks for three different patches, respectively. In the inference stage, we simply concatenate the features produced by the three networks. We have not used PCA to reduce the dimension, but PCA is optional here (potentially you could get better performance).

**Comment by CasiaFan** [comment]
@wy1iu Thanks for you response! But how do you choose the patches? Crop patches from aligned face region centered at some particular landmarks then resize to 96x112 before inputting to networks? Or just randomly crop with given size from initial face region?

**Comment by wy1iu** [comment]
Usually we crop the face images centered at some particular landmarks, since you have to align all your training samples and testing samples. You could use cross-validation to decide how many patches and which patches you want to ensemble.

**Comment by JoyLuo** [comment]
Hi @wy1iu  
    "For all experiments, the final representation of a testing face is obtained by concatenating its original face features and its horizontally flipped features." It is to say, the length of 3-patch concatenating feature is 512 * 2 *3 ? 
    and could you tell me the accuracy position and scale of the patch for reproduce the experiment ?
    Thanks a lot.

**Comment by JoyLuo** [comment]
Hi @CasiaFan 
could you tell me the guideline to crop the multi-patch of face ?
