### ISSUE TITLE
关于video demo

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [wy1iu/sphereface#21]
在video demo 里 ， 人脸框并不是正的，这是怎么实现的？MTCNN冰没有这个功能啊？

**Comment by yxchng** [comment]
@ZHAIXINGZHAIYUE 你知道怎么实现了吗？我也想了解

**Comment by happynear** [comment]
@yxchng 
https://github.com/happynear/MTCNN_face_detection_alignment/blob/master/code/codes/vs/Test/test.cpp#L222
