### ISSUE TITLE
Accuracy on LFW dataset

### ISSUE THREAD

**Issue by xizi** [wy1iu/sphereface#22]
Hi,@wy1iu，i used the 20 layers network trained on casita dataset and extract feature on lfw dataset by concate original face image and flip face image features and finally get 98.97% accuracy, is is normal?  I write a 64 layers network according to your paper and finally get 98.88% accuracy, why the deeper network get a worse result?

**Comment by double-vane** [comment]
@xizi Hi, Do you mind publishing your log?  Did you use cross validation?
Best!

**Comment by wy1iu** [comment]
Sorry, I am not able to comment anything without knowing the detailed setup. Using deeper network generally improves the performance.
