### ISSUE TITLE
Is there any SphereFace implementation on MXNet?

### ISSUE THREAD

**Issue by huyangc** [wy1iu/sphereface#23]

**Comment by tornadomeet** [comment]
you can add 2 line to change lsoftmax to asoftmax: https://github.com/luoyetx/mx-lsoftmax

**Comment by huyangc** [comment]
Thank you!

**Comment by zouxinh** [comment]
@tornadomeet , yes, lsoftmax is similar to asoftmax, but I am confuse how to normalize weight in mxnet?
