### ISSUE TITLE
训练的收敛问题

### ISSUE THREAD

**Issue by thuhuwei** [wy1iu/sphereface#25]
完全按照步骤要求进行训练，唯一的区别是限于只有单个6G显存的980T，只能单GPU以128的batchsize进行训练。始终不能收敛，请问这是batchsize过小引起的收敛问题吗？ 谢谢！

**Comment by wy1iu** [comment]
It is possible, but we did not try small batch size. I think different batch size may require different lambda decay strategy. You can try to tune the hyperparameter for lambda decay.
