### ISSUE TITLE
softmaxloss layer: num_output 10572

### ISSUE THREAD

**Issue by DL-85** [wy1iu/sphereface#35]
Since the WebFace contains 10,575 subjects, why using 10572?
Is that because mtcnn could only detect and align 10572 persons?

I'm using a face detection model and alignment method trained by myself.

**Comment by happynear** [comment]
There are 3 identities overlap between CASIA-Webface and LFW. They are 0166921, 1056413 and 1193098. For fair evaluation, it is recommended to remove them from CAISA-Webface.

**Comment by DL-85** [comment]
Ok, got it. Thanks @happynear
