### ISSUE TITLE
how to set theta range in [0,pi/m]

### ISSUE THREAD

**Issue by fromwhzz** [wy1iu/sphereface#39]
I check the code, I think it can not ensure the theta in [0,pi/m]. if the theta is not in the [0,pi/m], I think it will be some wrong.

**Comment by wy1iu** [comment]
theta does not need to be in [0,pi/m]. The paper has already expalined the reasons.

**Comment by fromwhzz** [comment]
I re-read the paper, I find the function to get rid of this restriction. thanks for your reply.
