### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by bkj** [wy1iu/sphereface#4]
Are you able to explain a couple of bits about the implementation of the `margin_inner_product_layer`?

1) What is `lambda_`?  It looks like it's a constant that decreases w/ the iterations, but doesn't seem to be mentioned in the paper.  ** Edit: Looks like you mix `x'w` and `margin(x'w)` via `(margin(x'w) + lambda_ * x'w) / (1 + lambda_)` where `lambda_` decreases exponentially w/ iterations.  Is that right?  **

2) What is the `type` parameter? (eg. `SINGLE, DOUBLE, TRIPLE, QUADRUPLE`)  I'm guessing this is how you set the value of `m` from the paper? ** Edit: I gather these are ways of implementing the margin for `m={1,2,3,4}`.  Any particular reason why you implemented this way?  Numerical stability? **

Thanks

**Comment by wy1iu** [comment]
Thanks @melgor for answering the questions.  :)
