### ISSUE TITLE
Questions abou alignment coordinate points

### ISSUE THREAD

**Issue by zzw1123** [wy1iu/sphereface#53]
In face_align_demo.m,there are 5 coordinate points used for alignment,so the question is how you get the values of them?
Are they located in the original image which is 250 * 250,or the 112 * 96 cropped image?

**Comment by qixianbiao** [comment]
These 5 coordinate points are created and provided by mtcnn face detector. They are used to align the faces, so you can crop 112*96 images from the aligned faces.

**Comment by zzw1123** [comment]
@qixianbiao Thanks,but I mean these 5 points which are valued by the author:
 
![image](https://user-images.githubusercontent.com/16879220/32768157-91132898-c951-11e7-9228-1f980ce9fd05.png)

**Comment by qixianbiao** [comment]
this should be a preset position template for the eyes, nose, and mouse.  You can google "python opencv face alignment" to find some information...

**Comment by qixianbiao** [comment]
this should be a preset position template for the eyes, nose, and mouth. You can google "python opencv face alignment" to find some information...

**Comment by zzw1123** [comment]
@qixianbiao Thanks a lot!Learned a lot about "Matrix Projection"!

**Comment by liuqunzhong** [comment]
after mtcnn， points of some faces maybe bad，especialy large pose。ow to deal with these faces

**Comment by vedrusss** [comment]
Hi Weiyang Liu,

Which parameters have you used for MTCNN while extracting LFW landmark points?
I'm trying to replicate your results. I did converted points returned from MTCNN from (x1,x2,x3,x4,x5,y1,y2,y3,y4,y5) to (x1,y1,...,x5,y5) before passing them to your 'alignment' function. But best estimations I have achieved are acc=96,3% / rec=93,3%.
To obtain facial landmarks from MTCNN face detector I've used default parameters (minsize = 20, treshold = [0.6, 0.7, 0.8]). Did you use the same or own?

Thanks, Alexey

**Comment by vedrusss** [comment]
Next question is 
can I use those hardcoded rer_points while aligning other datasets, faces onto other images?
I guess no, because they are obtained as mean position for LFW images, aren't they?

**Comment by HaoLiuHust** [comment]
I have the same question, I want to use 68 landmarks to align the face, but I do not know how to get 68 reference points

**Comment by zzw1123** [comment]
@HaoLiuHust I remember that dlib have a pretrained model which can align faces producing 68 landmarks,you can google it.

**Comment by HaoLiuHust** [comment]
@zzw1123 Thank your for your reply, actually I already have a 68 point facial landmarks detector, and I want to use these 68 points to align the face to a front pose, and then use the aligned faces to train a face recognizer, but I do not know how to get a 68 reference points to make a transform just as sphere face use 5 points do, do you have some advice？

**Comment by vedrusss** [comment]
I think you may run a set of cropped aligned faces (all images of same size) through your dlib landmarks extractor and then calculate mean positions of those 68 facial points.
It's no matter where they are located. But their locations relative to each other is important.

**Comment by HaoLiuHust** [comment]
@vedrusss thanks, I will have a try
