### ISSUE TITLE
Face Verification

### ISSUE THREAD

**Issue by spantazi** [wy1iu/sphereface#85]
@wy1iu Can someone use directly the output of fc5 to verify if a person is the same across multiple photos (with L2 distance for example)?

**Comment by wy1iu** [comment]
You can directly use it and probably you can still get decent accuracy, but it may not work as good as the cosine distance (because we are optimizing the angular margin). 

If you normalize the FC5 features, then using L2 distance will be equivalent to the cosine/angular distance.

**Comment by spantazi** [comment]
Thank you
